linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - prealloc
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goimports:
    local-prefixes: github.com/FabioSM46/network-stability-logger
